# Generated by Django 4.2.2 on 2023-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizencontractor',
            name='tender_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
