# Generated by Django 4.2.2 on 2023-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_citizencontractor_tender_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizencontractor',
            name='tender_title',
            field=models.CharField(default='Untitled', max_length=100, null=True),
        ),
    ]
