# Generated by Django 4.2.2 on 2023-06-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_citizencontractor_tender_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_title', models.CharField(default='Untitled', max_length=100, null=True)),
                ('tender_ref', models.CharField(max_length=100, unique=True)),
                ('tender_files', models.FileField(upload_to='tenders/')),
                ('addendums', models.FileField(blank=True, upload_to='addendums/')),
                ('certifications', models.FileField(blank=True, upload_to='certifications/')),
                ('drawings', models.FileField(blank=True, upload_to='drawings/')),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenNational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_title', models.CharField(default='Untitled', max_length=100, null=True)),
                ('tender_ref', models.CharField(max_length=100, unique=True)),
                ('tender_files', models.FileField(upload_to='tenders/')),
                ('addendums', models.FileField(blank=True, upload_to='addendums/')),
                ('certifications', models.FileField(blank=True, upload_to='certifications/')),
                ('drawings', models.FileField(blank=True, upload_to='drawings/')),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservedPWD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_title', models.CharField(default='Untitled', max_length=100, null=True)),
                ('tender_ref', models.CharField(max_length=100, unique=True)),
                ('tender_files', models.FileField(upload_to='tenders/')),
                ('addendums', models.FileField(blank=True, upload_to='addendums/')),
                ('certifications', models.FileField(blank=True, upload_to='certifications/')),
                ('drawings', models.FileField(blank=True, upload_to='drawings/')),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservedWomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_title', models.CharField(default='Untitled', max_length=100, null=True)),
                ('tender_ref', models.CharField(max_length=100, unique=True)),
                ('tender_files', models.FileField(upload_to='tenders/')),
                ('addendums', models.FileField(blank=True, upload_to='addendums/')),
                ('certifications', models.FileField(blank=True, upload_to='certifications/')),
                ('drawings', models.FileField(blank=True, upload_to='drawings/')),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservedYouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_title', models.CharField(default='Untitled', max_length=100, null=True)),
                ('tender_ref', models.CharField(max_length=100, unique=True)),
                ('tender_files', models.FileField(upload_to='tenders/')),
                ('addendums', models.FileField(blank=True, upload_to='addendums/')),
                ('certifications', models.FileField(blank=True, upload_to='certifications/')),
                ('drawings', models.FileField(blank=True, upload_to='drawings/')),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
            ],
        ),
    ]
