# Generated by Django 4.2.2 on 2023-06-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_openinternational_opennational_reservedpwd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='citizencontractor',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AddField(
            model_name='citizencontractor',
            name='procurement_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.procurementmethod'),
        ),
        migrations.AddField(
            model_name='openinternational',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AddField(
            model_name='openinternational',
            name='procurement_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.procurementmethod'),
        ),
        migrations.AddField(
            model_name='opennational',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AddField(
            model_name='opennational',
            name='procurement_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.procurementmethod'),
        ),
        migrations.AddField(
            model_name='reservedpwd',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AddField(
            model_name='reservedpwd',
            name='procurement_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.procurementmethod'),
        ),
        migrations.AddField(
            model_name='reservedwomen',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AddField(
            model_name='reservedwomen',
            name='procurement_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.procurementmethod'),
        ),
        migrations.AddField(
            model_name='reservedyouth',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AddField(
            model_name='reservedyouth',
            name='procurement_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.procurementmethod'),
        ),
    ]
