# Generated by Django 4.2.2 on 2023-06-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_category_procurementmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awarded_to', models.CharField(max_length=100)),
                ('tender_title', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'your_app_name'), ('model', 'citizencontractor')), models.Q(('app_label', 'your_app_name'), ('model', 'openinternational')), models.Q(('app_label', 'your_app_name'), ('model', 'opennational')), models.Q(('app_label', 'your_app_name'), ('model', 'reservedpwd')), models.Q(('app_label', 'your_app_name'), ('model', 'reservedwomen')), models.Q(('app_label', 'your_app_name'), ('model', 'reservedyouth')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
