# Generated by Django 4.2.2 on 2023-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizencontractor',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='citizencontractor',
            name='awarded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openinternational',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='openinternational',
            name='awarded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opennational',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opennational',
            name='awarded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservedpwd',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservedpwd',
            name='awarded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservedwomen',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservedwomen',
            name='awarded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservedyouth',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservedyouth',
            name='awarded',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Awarded',
        ),
    ]
