# Generated by Django 4.2.2 on 2023-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_citizencontractor_amount_citizencontractor_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizencontractor',
            name='awarded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openinternational',
            name='awarded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opennational',
            name='awarded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservedpwd',
            name='awarded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservedwomen',
            name='awarded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservedyouth',
            name='awarded_status',
            field=models.BooleanField(default=False),
        ),
    ]
