# Generated by Django 4.2.2 on 2023-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_category_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='duns_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms')], max_length=50),
        ),
    ]
