# Generated by Django 4.2.2 on 2023-06-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_supplier_duns_number_alter_supplier_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product_category',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_category',
            field=models.ManyToManyField(to='main.product_category'),
        ),
    ]
